### ISSUE TITLE
Conditionally exclude h1

### ISSUE THREAD

**Issue by dobbymoodge** [ardumont/markdown-toc#16]
I tend to organize my docs like:

```
# Title of Document
[table of contents]
## Section 1
### Subsection a
## Section 2
...
```

I would like to be able to tell `markdown-toc-generate-toc` not to include "Title of Document" in the generated TOC.

**Comment by ardumont** [comment]
Hello,

see https://github.com/ardumont/markdown-toc#user-toc-manipulation for some example on how to meet your use case.

Cheers,

**Comment by dobbymoodge** [comment]
Thanks! I'll test it out soon.

On Wed, Dec 23, 2015 at 6:17 AM, Antoine R. Dumont <notifications@github.com

**Comment by dobbymoodge** [comment]
This works great, although if for example the structure post-manipulation doesn't have any bottom-level elements, the generated TOC is indented 4 spaces, yielding something like this:

    - [My first TOC entry](#my-first-toc-entry)
        - [Subsection 1](#subsection-1)
    - [My second TOC entry](#my-second-toc-entry)


Maybe you could normalize the structure automatically so that the bottom-most level in the output always gets placed at column 1, like so:

- [My first TOC entry](#my-first-toc-entry)
    - [Subsection 1](#subsection-1)
- [My second TOC entry](#my-second-toc-entry)

**Comment by ardumont** [comment]
> This works great, 

Awesome!

> Actually, I'll create a new issue for this

Nice reflex, thanks a bunch!

Cheers,
