### ISSUE TITLE
Always start TOC on first column

### ISSUE THREAD

**Issue by dobbymoodge** [ardumont/markdown-toc#18]
if for example the structure post-manipulation doesn't have any bottom-level elements, the generated TOC is indented 4 spaces, yielding something like this:

    - [My first TOC entry](#my-first-toc-entry)
        - [Subsection 1](#subsection-1)
    - [My second TOC entry](#my-second-toc-entry)

Maybe you could normalize the structure automatically so that the bottom-most level in the output always gets placed at column 1, like so:

- [My first TOC entry](#my-first-toc-entry)
    - [Subsection 1](#subsection-1)
- [My second TOC entry](#my-second-toc-entry)

**Comment by ardumont** [comment]
Hello again,

Actually, you could already do that yourself in the user-customed function you define.

For example, you could define a function that maps the entries and decreases the level by 1 for each entry. So, something like:

```lisp
(require 'dash)
(custom-set-variables '(markdown-toc-user-toc-structure-manipulation-fn
                        (lambda (toc-structure)
                          (--map (-let (((level . label) it))
                                   (cons (- level 1) label))
                                 toc-structure))))
```

Provided you want to drop the first h1 in your list as in #16, you may prefer something like:

```lisp
(custom-set-variables '(markdown-toc-user-toc-structure-manipulation-fn
                        (lambda (toc-structure)
                          (--map (-let (((level . label) it))
                                   (cons (- level 1) label))
                                 (cdr toc-structure)))))
```
Which drops the first h1 and then decrease each level by 1.
Thus having the rendered TOC you want.

# Tryouts

## playground

Here is a sample to play some more:

```lisp
((lambda (toc-structure)
   (--map (-let (((level . label) it))
            (cons (- level 1) label))
          (cdr toc-structure)))

 '((0 . "main title")
   (1 . "Sources")
   (2 . "Marmalade (recommended)")
   (2 . "Melpa-stable")
   (2 . "Melpa (~snapshot)")
   (1 . "Install")
   (2 . "Load org-trello")
   (2 . "Alternative")
   (3 . "Git")
   (3 . "Tar")))
```

Copy that in a scratch buffer and <kbd>M-x eval-buffer</kbd> to execute and see the result.
Or <kbd>M-x ielm</kbd> to play in emacs' repl.

# Buffer 

My sample set with actual result of previous code.

```md
<!-- markdown-toc start - Don't edit this section. Run M-x markdown-toc-generate-toc again -->
**Table of Contents**

- [Sources](#sources)
    - [Marmalade (recommended)](#marmalade-recommended)
    - [Melpa-stable](#melpa-stable)
    - [Melpa (~snapshot)](#melpa-snapshot)
- [Install](#install)
    - [Load org-trello](#load-org-trello)
    - [Alternative](#alternative)
        - [Git](#git)
        - [Tar](#tar)

<!-- markdown-toc end -->
To install **org-trello** in your emacs, you need a few steps.
# blah
## Sources
If not already configured, you need to prepare emacs to work with marmalade or melpa.
For this, you need to install a snippet of code in your emacs configuration file.
### Marmalade (recommended)
### Melpa-stable
### Melpa (~snapshot)
## Install
### Load org-trello
### Alternative
#### Git
#### Tar
```


Cheers,

**Comment by ardumont** [comment]
Without any replies, i can only assume it's ok now.
Feel free to reopen with more feedback.

Cheers,

**Comment by dobbymoodge** [comment]
right, sorry, this is good now. :D

**Comment by ardumont** [comment]
Cool.
Thx for the feedback.
Cheers,
