### ISSUE TITLE
Symbol's function definition is void: markdown-imenu-create-index

### ISSUE THREAD

**Issue by waynr** [ardumont/markdown-toc#20]
https://github.com/ardumont/markdown-toc/blob/master/markdown-toc.el#L201
https://github.com/jrblevin/markdown-mode/commit/44204334b3f01fcaed34d9596e1fdec219580619

This method has not been in the `markdown-mode` for almost two years. I don't understand why I was able to use markdown-toc earlier this month, but it's pretty obviously borked now.

**Comment by ardumont** [comment]
Hello,

Maybe we both had an old version of markdown-mode drawn from package.

Thanks for raising this up and thanks for the possible fix.

I can't check right now though, not before next week (this includes the PR).

Cheers,

**Comment by Wilfred** [comment]
Funny, I've just bumped into this too. I'm mystified as to why it's just changed now.

**Comment by ardumont** [comment]
Hello, i've merged the PR.

For information, after updating my local fork and running the tests, they failed.
So, i've updated my local cask install (cask runs the tests in a chroot-ish env) and we can see that markdown-mode is updated (last line of the following sample) from 20151222.1030 to 20160121.528 (melpa unstable)

Then running the tests again and it's all ok (which reflects the travis-ci's result in PR, that is green).
So this function must have been removed recently (from within the last 2 months or so, not years...).

Anyway, here is the sample:
```sh 
# tony at corellia in ~/repo/perso/markdown-toc on git:master o [17:59:46]
$ cask update
Making version-control local to s-autoloads.el while let-bound!
Wrote /home/tony/repo/perso/markdown-toc/.cask/24.5.2/elpa/s-20160115.58/s-autoloads.el
Wrote /home/tony/repo/perso/markdown-toc/.cask/24.5.2/elpa/markdown-mode-20160121.528/markdown-mode-autoloads.el
Updated packages:
s 20150924.406 -> 20160115.58
markdown-mode 20151222.1030 -> 20160121.528
```

And thanks again for your help.

Cheer
