### ISSUE TITLE
Not working on emacs 24.5

### ISSUE THREAD

**Issue by drym3r** [ardumont/markdown-toc#22]
Hi,
I just installed emacs 24.5 and (markdown-toc-generate-toc) has stopped working. It says: 
markdown-toc-generate-toc: Symbol's function definition is void: markdown-imenu-create-index

Any idea?
PD: thanks for your work, is not easy to find a toc creator that doesn't rely on node.

**Comment by ardumont** [comment]
Hello,

What is your current version ans installation choice (melpa, marmalade,
etc...)?

Thanks for the precision.

Cheets,

**Comment by ardumont** [comment]
Precision: this should have been fixed with the latest version (0.0.9) #20 

Cheers,

**Comment by ardumont** [comment]
Hello again,

I've made a new release that update markdown-toc's dependencies (markdown-mode specifically).
But also <kbd>M-x markdown-toc-bug-report</kbd>.

If your problem persists, please report the output of <kbd>M-x markdown-toc-bug-report</kbd> here.

Thanks for your feedback.

Cheers,

**Comment by drym3r** [comment]
I'm using markdown-toc 0.0.9 and I installed via melpa. I just upgraded and everything works fine now, thank you.

**Comment by ardumont** [comment]
> I'm using markdown-toc 0.0.9 and I installed via melpa. I just upgraded and everything works fine now, thank you.

Thanks for your feedback.
