### ISSUE TITLE
Make `markdown-toc--header-toc-title` customizable

### ISSUE THREAD

**Issue by rpls** [ardumont/markdown-toc#26]
Would it be possible to make `markdown-toc--header-toc-title` customizable, e.g. by using `defcustom` instead of `defconst`? This way, users could Localize the String on a global or per-document basis.

**Comment by ardumont** [comment]
Hello,

> This way, users could Localize the String on a global or per-document basis.

Awesome idea ^^

Cheers,

**Comment by rpls** [comment]
You have a typo in the group of the variables =)

`:group 'mardown-toc`

**Comment by ardumont** [comment]
Thx!
