### ISSUE TITLE
Need to insert empty line before TOC header

### ISSUE THREAD

**Issue by twekberg** [ardumont/markdown-toc#30]
I was having trouble getting the TOC to display properly. 

### System information:
- system-type: gnu/Linux
- os: Ubuntu 14.04.3 LTS
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)
 of 2014-03-07 on lamiak, modified by Debian
- markdown-toc version: 0.1.2
- markdown-toc path: /home/tekberg/.emacs.d/elpa/markdown-toc-20160727.908/markdown-toc.el

### Expected behavior

I ran M-x markdown-toc-generate-toc to (re)generate the TOC. Then I ran M-x markdown-preview. I expected to see something line this:

```
    Table of Contents

	Introduction
	Ansible Instructions
	Role Documentation
	    Logwatch
	    Duply
		Install Duply
		    Variables
		    Automatic Settings
		Duply Setup
```

### Actual behavior

What I actually got was this:
```
**Table of Contents** - [Introduction](#introduction) - [Ansible Instructions](#ansible-instructions) - [Role Documentation](#role-documentation) - [Logwatch](#logwatch) - [Duply](#duply) - [Install Duply](#install-duply) - [Variables](#variables) - [Automatic Settings](#automatic-settings) - [Duply Setup](#duply-setup) 
```

### Steps to reproduce the behavior

Create a file bar.md with this contents

    # First
    First section.

    # Second
    Second section.

Run M-x markdown-toc-generate-toc to generate the TOC. Then run M-x markdown-preview. You will see something like this:

     **Table of Contents** 59f3daaf7f3ba5d330794074fe78c457 

If you add a \n before the TOC header you will see this:

    Table of Contents

        First
        Second

### What do you want?
Either insert the \n in the lisp code or change the default value of markdown-toc-header-toc-title to be "\n**Table of Contents**". I did the latter.

### Why is it better?

It properly formats the TOC.

**Comment by ardumont** [comment]
Hello,

Awesome report.
I'll see what i can do.

Cheers,

**Comment by ardumont** [comment]
I actually don't reproduce this. Closing.
