### ISSUE TITLE
The comment mentioning how to regenerate the markdown TOC should mention which package the function is from (this one)

### ISSUE THREAD

**Issue by ahungry** [ardumont/markdown-toc#32]
I recently had a contributor of a package I maintain use the function `markdown-toc-generate-toc` in a project's README (as indicated by the comment this package leaves).

However, when coming across this comment, it is not immediately clear which package this function comes from.

I would suggest including a reference to the package name (markdown-toc) somewhere in the comment.

**Comment by ardumont** [comment]
Hello,

> I recently had a contributor of a package I maintain use the function markdown-toc-generate-toc in a project's README (as indicated by the comment this package leaves).

Awesome it was of some help :D

> I would suggest including a reference to the package name (markdown-toc) somewhere in the comment.

I thought the deduction from the prefix command was enough.
Apparentely, it's not enough. 
So sure, that sounds quite reasonable.

[It is defined on a per-user basis](https://github.com/ardumont/markdown-toc/blob/master/markdown-toc.el#L138).

What do you think of:
```html
<!-- markdown-toc start - Don't edit this section. With minor mode markdown-toc, run M-x markdown-toc-generate-toc again -->
```

Thanks for the feedback.

Cheers,

**Comment by ahungry** [comment]
I think that's pretty good.  While the prefix is not terrible, my first assumption was it was a function from 'markdown' mode (I viewed it as a prefix of markdown - disadvantage of Emacs using dash for prefix vs slashes which would actually provide a unique distinguishing mark I suppose)...

**Comment by ardumont** [comment]
> I think that's pretty good. 

Cool.

> While the prefix is not terrible, my first assumption was it was a function from 'markdown' mode (I viewed it as a prefix of markdown - disadvantage of Emacs using dash for prefix vs slashes which would actually provide a unique distinguishing mark I suppose)...

As a convention indeed, it's preferred to use dash instead of slash.
For your information, I started with / but came across the convention thing so i adapted to respect it.

Anyway, i'll adapt to it (I actually did but lost the commit, sh*t happens ):

Cheers,

**Comment by ardumont** [comment]
It's actually done so closing.
