### ISSUE TITLE
Lines starting with # in code sections are treated as headings

### ISSUE THREAD

**Issue by akopytov** [ardumont/markdown-toc#35]
## bug?

Leading hash symbols in code sections are interpreted as headings and the corresponding lines are added to TOC.

I have the following in my README.md:
```markdown
    ```shell
    # Add --with-postgresql if you need PostgreSQL support
    brew install sysbench
    ```
```

Note the leading hash symbol which is meant as a shell comment. However, markdown-toc apparently treats it as a heading, so the following ends up added to my TOC:

```markdown
- [Add --with-postgresql if you need PostgreSQL support](#add---with-postgresql-if-you-need-postgresql-support)
```
### Expected behavior

Ignore leading hash symbols in code sections.

### Actual behavior

Lines corresponding to lines with a leading # are added to TOC.

### Steps to reproduce the behavior

See above.

**Comment by ardumont** [comment]
That no longer happens \m/

Closing.

Feel free to reopen if you still encounter the issue.
