### ISSUE TITLE
How to follow the link in TOC?

### ISSUE THREAD

**Issue by patzhang** [ardumont/markdown-toc#42]
Hi,
First of all, thanks for the package.

I am using this package within the Markdown of Spacemacs.  I would like to follow the links in the TOC to the corresponding sections. I tried `SPC m f` (markdown-follow-thing-at-point), but it does not work with TOC.

Is it possible to follow the link? Or it is a new feature that can be implemented.

Looking forward to your reply. Thanks in advance.

**Comment by ardumont** [comment]
> Is it possible to follow the link?

I have no idea.
I did that to follow within the rendering of the readme in web pages.

But that'd be a good feature indeed.

**Comment by patzhang** [comment]
Thanks for the reply.

The "links" in TOC are [anchors in Markdown](https://gist.github.com/asabaylus/3071099).

It will be useful to be able to follow these anchors to navigate through a large document.

If this can be implemented in markdown-toc or [markdown-mode](https://github.com/jrblevin/markdown-mode), it will be very helpful.

Is it possible to mark this issue as a feature request? Thanks.

**Comment by ardumont** [comment]
^ naming is hard... ¯\_(ツ)_/¯

Feature in progress

Cheers,

**Comment by ardumont** [comment]
Landed in 0.1.5

M-x markdown-toc-follow-link-at-point

Closing this.

Cheers,
