### ISSUE TITLE
Generate invalid link when heading contains underscore `_`

### ISSUE THREAD

**Issue by hirose31** [ardumont/markdown-toc#43]
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 26.1 (build 1, x86_64-Ubuntu-linux-gnu, X toolkit, Xaw scroll bars)
 of 2019-03-12
- markdown-toc version: 0.1.2

heading contains underscore `_`:

```
# under_socre
```

github generate link `#under_score`
but markdown-toc generate `- [under_score][#undersocre]`.

Because `_` is matched `[[:punct:]]` so replace into `""` in `markdown-toc--to-link`.

**Comment by VladimirAlexiev** [comment]
Here is a fix

```elisp
(defun markdown-toc--to-link (title count)
  "Given a TITLE, return the markdown link associated."
  (format "[%s](#%s%s)" title
          (->> title
               downcase
               (replace-regexp-in-string "[^_[:alnum:]]" "-")
               (replace-regexp-in-string "-+" "-")
               (replace-regexp-in-string "^-" "")
               (replace-regexp-in-string "-$" ""))
          (if (> count 0)
            (concat "-" (number-to-string count))
            "")))
```

**Comment by ardumont** [comment]
Hello,

Thanks for the report and the proposal fix.

I don't think deal with the leading or trailing `_` are needed though.

This can be seen as typos. And the author can simply remove those.

Cheers,

**Comment by VladimirAlexiev** [comment]
@ardumont there may be legitimate reasons for a title to start with underscore. Eg someone is documenting some system variables or functions...

If github removes it, so should you
