### ISSUE TITLE
Consider a new maintainer/collaborator?

### ISSUE THREAD

**Issue by jcs090218** [ardumont/markdown-toc#61]
Thanks for this awesome package! 🚀 

The last commit was 3 years ago; therefore, I wonder if this package needs a maintainer. If so, I would like to volunteer myself.

Regarding myself, I serve as the primary maintainer for `emacs-dashboard` and one of the maintainers for `lsp-mode`. I have developed over a hundred Emacs packages. Hope I am qualified to help maintain this package.

**Comment by ardumont** [comment]
Hello, it sure sounds like you got the experience.

And indeed, I got side-tracked a lot by work, family business, and so on (in any order ;)

So, i've invited you to join as collaborator.

Shout out if you need something more.

Cheers,

**Comment by jcs090218** [comment]
Accepted! Thank you! :D
